In [1]:
import numpy as np

In [18]:
x = np.random.uniform(-1,1,3)
x

array([ 0.45365309, -0.36201106, -0.61260643])

In [19]:
y = np.random.uniform(-1,1,3)
y

array([0.20887517, 0.91480118, 0.78652607])

In [20]:
z = np.column_stack((x, y))
z

array([[ 0.45365309,  0.20887517],
       [-0.36201106,  0.91480118],
       [-0.61260643,  0.78652607]])

In [21]:
np.shape(z)

(3, 2)

In [24]:
np.dot(x, y)

-0.7182422058682015

In [ ]:
### For 1 dimensional arrays, dot calculates the product of the vectors i.e. 1*2 + 2*3 + 3*4 + 4*5

In [34]:
j = np.array([1,2,3,4])
k = np.array([2,3,4,5])
np.dot(j,k)

40

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
b

array([[11, 12],
       [13, 14]])

In [ ]:
### Matrix multiplication calculated as: [[1*11+2*13, 1*12 + 2*13],[3*13 + 4*14]]

In [31]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [28]:
np.shape(a)

(2, 2)