In [1]:
import numpy as np

In [21]:
x2 = np.random.randint(100, size=(5,5))

In [22]:
x2

array([[36, 37, 38, 44, 16],
       [ 2, 79, 18, 82, 65],
       [92, 59, 69, 43, 16],
       [45, 65, 47, 14, 41],
       [90, 54, 31, 19, 11]])

### Basic Array Manipulation

Select everything:  

In [23]:
x2[:,:]

array([[36, 37, 38, 44, 16],
       [ 2, 79, 18, 82, 65],
       [92, 59, 69, 43, 16],
       [45, 65, 47, 14, 41],
       [90, 54, 31, 19, 11]])

Select last element from the last row:

In [24]:
x2[-1,-1]

11

Select the last element for all rows:

In [25]:
x2[:,-1]

array([16, 65, 16, 41, 11])

Each dimension of the array is delineated by comma.  
Each colon (within each dimension) delineates the start, stop, and step through that dimension.  
-1 indicates the last element of the array.  
In a 2D array, to get all rows, ignoring the first and last columns:  
    

In [32]:
x2[:,1:-1:1]

array([[37, 38, 44],
       [79, 18, 82],
       [59, 69, 43],
       [65, 47, 14],
       [54, 31, 19]])

which is the same as (defaults to step by 1):

In [33]:
x2[:,1:-1]

array([[37, 38, 44],
       [79, 18, 82],
       [59, 69, 43],
       [65, 47, 14],
       [54, 31, 19]])

Shape returns the size of each dimension of the array as a tuple

In [17]:
x2.shape[0]

5

In [19]:
x5 = np.random.randint(5, size=(8,3))
x5.shape

(8, 3)

### Deletion  
Use np.delete to remove elements from an array

In [23]:
x3 = np.random.randint(10, size=(3,3))

array([[2, 6, 9],
       [8, 5, 0],
       [3, 4, 9]])

In [29]:
delete_me = (1,2)
np.delete(x3, delete_me, axis=1)

array([[2],
       [8],
       [3]])

In [32]:
type(delete_me)

tuple

### Append

In [40]:
my_tuple = (1,2,3,4)
my_list = [1,2,3,4]
print('Type of my_tuple is: '+str(type(my_tuple)))
print('Type of my_list is: '+str(type(my_list)))

Type of my_tuple is: <class 'tuple'>
Type of my_list is: <class 'list'>


Let's append to the list

In [41]:
my_list.append(5)
my_list

[1, 2, 3, 4, 5]

### Arange and Shuffle Indices!!
Arange gives you a range of evenly spaced values...

In [69]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x5 = np.random.randint(10, size=(5,5))
x5

array([[8, 4, 0, 9, 5],
       [0, 8, 3, 8, 5],
       [1, 6, 2, 4, 4],
       [6, 2, 1, 8, 0],
       [8, 3, 5, 3, 6]])

In [66]:
shuffled_indices = np.arange(x5.shape[0])

In [75]:
np.random.shuffle(shuffled_indices)

In [76]:
my_shuffled_rows = x5[shuffled_indices]
my_shuffled_rows

array([[1, 6, 2, 4, 4],
       [8, 3, 5, 3, 6],
       [6, 2, 1, 8, 0],
       [0, 8, 3, 8, 5],
       [8, 4, 0, 9, 5]])

In [77]:
my_shuffled_cols = x5[:,shuffled_indices]
my_shuffled_cols

array([[0, 5, 9, 4, 8],
       [3, 5, 8, 8, 0],
       [2, 4, 4, 6, 1],
       [1, 0, 8, 2, 6],
       [5, 6, 3, 3, 8]])

### Update Array

In [3]:
y3 = np.random.randint(10, size=(3,3))
y3

array([[0, 8, 3],
       [4, 7, 6],
       [4, 2, 0]])

In [4]:
y3[0,1]

8

In [5]:
y3[0,1] = 1
y3

array([[0, 1, 3],
       [4, 7, 6],
       [4, 2, 0]])